apiVersion: operator.broker.platform-mesh.io/v1alpha1
kind: Broker
metadata:
  name: resource-broker
  namespace: resource-broker-system
spec:
  image:
    repository: resource-broker
    tag: dev
  extraArgs:
    - "-kubeconfig=/kubeconfigs/platform/kubeconfig"
    - "-coordination-kubeconfig=/kubeconfigs/platform/kubeconfig"
    - "-compute-kubeconfig=/kubeconfigs/platform/kubeconfig"
    - "-consumer-kubeconfig=/kubeconfigs/consumer/kubeconfig"
    - "-provider-kubeconfig=/kubeconfigs/internalca/kubeconfig,/kubeconfigs/externalca/kubeconfig"
    - "-zap-devel=true"
    - "-watch-kind=Certificate.v1alpha1.example.platform-mesh.io"
  volumes:
    - name: kubeconfig-platform
      secret:
        secretName: kubeconfig-platform
    - name: kubeconfig-consumer
      secret:
        secretName: kubeconfig-consumer
    - name: kubeconfig-internalca
      secret:
        secretName: kubeconfig-internalca
    - name: kubeconfig-externalca
      secret:
        secretName: kubeconfig-externalca
  volumeMounts:
    - name: kubeconfig-platform
      mountPath: /kubeconfigs/platform
      readOnly: true
    - name: kubeconfig-consumer
      mountPath: /kubeconfigs/consumer
      readOnly: true
    - name: kubeconfig-internalca
      mountPath: /kubeconfigs/internalca
      readOnly: true
    - name: kubeconfig-externalca
      mountPath: /kubeconfigs/externalca
      readOnly: true
