group "default" {
  targets = [
    "resource-broker",
    "resource-broker-kcp",
  ]
}

variable "REGISTRY" {
  type    = string
  default = "ghcr.io"
}

variable "ORG" {
  type    = string
  default = "platform-mesh"
}

target "docker-metadata-action" {
  tags = ["latest"]
}

target "resource-broker" {
  inherits = ["docker-metadata-action"]
  context = "."
  dockerfile = "Dockerfile"
  # this is so in the workflow the tags generated by
  # docker/metadata-action can be reused for all targets in the bake
  # file and not having to duplicate the logic for every image.
  tags = [for tag in target.docker-metadata-action.tags : "${REGISTRY}/${ORG}/resource-broker:${tag}"]
  platforms = [
    "linux/amd64",
    "linux/arm64",
  ]
}

target "resource-broker-kcp" {
  inherits = ["docker-metadata-action"]
  context = "."
  dockerfile = "contrib/kcp/Dockerfile"
  tags = [for tag in target.docker-metadata-action.tags : "${REGISTRY}/${ORG}/resource-broker-kcp:${tag}"]
  platforms = [
    "linux/amd64",
    "linux/arm64",
  ]
}
