apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: certificates.example.platform-mesh.io
spec:

  schema:
    group: example.platform-mesh.io
    apiVersion: v1alpha1
    kind: Certificate
    spec:
      fqdn: string
    status:
      status: ${certificate.status.conditions.exists(c, c.type == "Ready" && c.status == "True") ? "Available":"Unavailable"}
      conditions: ${certificate.status.conditions}
      relatedResources:
        secret:
          gvk:
            group: ${secret.apiVersion == "v1" ? "core":secret.apiVersion.split("/")[0]}
            version: ${secret.?apiVersion}
            kind: ${secret.?kind}
          name: ${secret.metadata.name}
          namespace: ${secret.metadata.namespace}

  resources:

    - id: certificate
      template:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          commonName: ${schema.spec.fqdn}
          secretName: ${schema.metadata.name}
          privateKey:
            algorithm: ECDSA
            size: 256
          issuerRef:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
            group: cert-manager.io

    - id: secret
      externalRef:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${certificate.metadata.name}
          namespace: ${certificate.metadata.namespace}
