apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  name: vms.example.platform-mesh.io
spec:
  gvr:
    group: example.platform-mesh.io
    version: v1alpha1
    resource: vms
  filters:
    - key: memory
      boundary:
        min: 1024
        max: 8192
---
apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  name: pgs.example.platform-mesh.io
spec:
  gvr:
    group: example.platform-mesh.io
    version: v1alpha1
    resource: pgs
  filters:
    # Nestor doesn't want to deal with small postgres instances, so they
    # set a minimum of 5GiB storage. At the same time they can't
    # reliably handle larger instances, so they set a maximum of 9TiB.
    - key: storage.size
      boundary:
        min: 5
        max: 9216
