apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: pgs.example.platform-mesh.io
spec:

  schema:
    group: example.platform-mesh.io
    apiVersion: v1alpha1
    kind: PG
    spec:
      storage:
        size: integer | required=true
    status:
      conditions: ${cluster.status.conditions}
      relatedResources:
        secret:
          gvk:
            group: core
            version: v1
            kind: Secret
          name: ${cluster.metadata.name + "-app"}
          namespace: ${cluster.metadata.namespace}
        hostSecret:
          gvk:
            group: core
            version: v1
            kind: Secret
          name: ${cluster.metadata.name + "-host"}
          namespace: ${cluster.metadata.namespace}
        clientCASecret:
          gvk:
            group: core
            version: v1
            kind: Secret
          name: ${cluster.status.certificates.clientCASecret}
          namespace: ${cluster.metadata.namespace}

  resources:

    - id: cluster
      template:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: ${schema.metadata.name}
        spec:
          storage:
            size: ${schema.spec.storage.size}Gi
          managed:
            services:
              additional:
                - selectorType: rw
                  serviceTemplate:
                    metadata:
                      name: ${schema.metadata.name}-nodeport
                    spec:
                      type: NodePort

    - id: service
      externalRef:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.metadata.name}-nodeport
          namespace: ${schema.metadata.namespace}

    - id: hostSecret
      template:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${schema.metadata.name}-host
          namespace: ${schema.metadata.namespace}
        type: Opaque
        stringData:
          host: broker-cloud-control-plane
          # without the conversion the port is interpreted as value.valueUnstructured and errors
          port: ${string(service.spec.ports[0].nodePort)}
