apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-broker
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-broker
rules:
  # These broker CRDs are not needed on the consumer but mcmanager
  # currently requires all CRDs to be installed (see #132).
  - apiGroups:
      - broker.platform-mesh.io
    resources:
      - acceptapis
      - migrationconfigurations
      - migrations
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - broker.platform-mesh.io
    resources:
      - acceptapis/finalizers
      - migrationconfigurations/finalizers
      - migrations/finalizers
    verbs:
      - update
  - apiGroups:
      - broker.platform-mesh.io
    resources:
      - acceptapis/status
      - migrationconfigurations/status
    verbs:
      - get
  - apiGroups:
      - broker.platform-mesh.io
    resources:
      - migrations/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - example.platform-mesh.io
    resources:
      - certificates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - example.platform-mesh.io
    resources:
      - certificates/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - example.platform-mesh.io
    resources:
      - certificates/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-broker
subjects:
  - kind: ServiceAccount
    name: resource-broker
    namespace: default
