apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  # name can be anything but for simplicity we use the GR of the
  # accepted API
  name: vms.example.platform-mesh.io
spec:
  gvr:
    group: example.platform-mesh.io
    version: v1alpha1
    resource: vms
  filters:
    - key: memory
      boundary:
        max: 1024
---
apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  name: pgs.example.platform-mesh.io
spec:
  gvr:
    group: example.platform-mesh.io
    version: v1alpha1
    resource: pgs
  filters:
    # Theseus only handles small postgres instances, so they set
    # a maximum of 5GiB storage
    - key: storage.size
      boundary:
        max: 5
